### ISSUE TITLE
Metadata for samples file?

### ISSUE THREAD

**Issue by awohns** [tskit-dev/tsinfer#109]
Is there a way to add metadata to a samples file? I see a way to add it for individuals and populations, but not at the top-level (i.e. for the whole file).

**Comment by jeromekelleher** [comment]
Not currently, no. What sort of thing did you want to add? There is a way to add provenance information (which is supposed to track where files came from and how they were generated).

**Comment by awohns** [comment]
Provenance information was sort of what Yan and I were thinking of. For instance, when we make a sample file showing which vcf, PED file etc. it came from.

**Comment by hyanwong** [comment]
Ah, OK. It just needs documenting, I guess. Missed that line, thanks!

**Comment by hyanwong** [comment]
@jeromekelleher: what can I add as parameters to `record_provenance()`. Obviously command=X, args=Y, but can I also invent my own params, e.g. file_urls=my_json_string. It is useful to be able to trace where the various different files come from that are combined into the samples file (e.g. variants from a set of 1000G liftover files, pedigree data from somewhere else, ancestral states from somewhere yet again).

**Comment by jeromekelleher** [comment]
You can put whatever you want in there, basically, once it's JSON encodable. See [here](https://msprime.readthedocs.io/en/stable/provenance.html) for more information on  tskit provenance in general.

**Comment by hyanwong** [comment]
Great, thanks. I was looking for this in the tsinfer docs, which is why I missed it.

**Comment by hyanwong** [comment]
@jeromekelleher : how about adding a "data_files" item, which itself contains a dictionary listing the data files used in the command, and how they were obtained. If they are simple downloads, we can use e.g. `downloaded_from` as an item. If they were generated by another program, we can nest the program names in a `parameters` key. Like this:

```
{
  "parameters": {
    "command": "treeseq-inference/src/convert_1kg.py",
    "args": ["ALL.chr1_GRCh38.genotypes.20170504.vcf.gz", "20130606_g1k.ped", "H_sap_chr1.samples", "-a" "homo_sapiens_chr1.vcf.gz","-p"],
    "data_files": {
        "ALL.chr1_GRCh38.genotypes.20170504.vcf.gz": {
            "downloaded_from":"http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/supporting/GRCh38_positions/ALL.chr1_GRCh38.genotypes.20170504.vcf.gz"
        },
        "20130606_g1k.ped": {
            "downloaded_from":"ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/working/20130606_sample_info/20130606_g1k.ped"
        },
        "homo_sapiens_chr1.vcf.gz": {
            "parameters":{
                "command": "bcftools",
                "args": ["view", "homo_sapiens.vcf.gz", "--regions", "-Oz", "-o", "homo_sapiens_chr1.vcf.gz"],
                "data_files": {
                    "homo_sapiens.vcf.gz": {
                        "downloaded_from":"ftp://ftp.ensembl.org/pub/release-91/variation/vcf/homo_sapiens/homo_sapiens.vcf.gz"
                    }
                }
            }
        }
    }
  }
}
```

If I download files from the internet using curl --xattr -O, then the original download URL can be retrieved from the extended attributes stored on the download file, so most of the construction of this provenance information can be done automatically.

**Comment by jeromekelleher** [comment]
I like the ``data_files`` idea, that's a good way of recording this stuff. It's probably better to just record the URLS (or probably base url) directly in the provenance rather than trying to make it work automatically. I think relying on stuff like xattrs will make it brittle in practise.

If you really wanted to make this full reproducible, the way to go is to have a Makefile which downloads the files directly, and does the file preparation. The provenance information could them encode the git URL and hash (probably provided as a command line arg to the script). Then to reproduce you just clone the git repo, and run 'make'.

**Comment by hyanwong** [comment]
OK. I'll go with `data_files`. I think you misunderstood me about the URLs though. I simply want a way to get hold of the original URL in order to *put it* into the TS provenance information. I don't really want to re-download these large files each time, so am trying to use the already-downloaded versions. However, the download URL is not recorded in an obvious way in the VCF file (although the filename e.g. `ALL.chr1_GRCh38.genotypes.20170504.vcf.gz` is usually enough to work out where it came from). 

Helpfully, however, if you download these files using `curl --xattr`, the original URL is stored in an extended attribute of the .gz file, so an easy extra step would be to look for that xattr in the downloaded file, and it if exists, stick the URL into the provenance automatically. If not, I guess provenance can be derived from the filename.

I've just seen that the holly user dirs are mounted on an xfs filesystem, which does support extended attributes. So this is an easy win.

**Comment by jeromekelleher** [comment]
I see where you're coming from witg the xattrs, I just think it'll be brittle in practise. A makefile which fully automates is a better solution, and if we record the git URL and hash in the provenance, we'll know where to find that make file.

**Comment by hyanwong** [comment]
Yep, it's just that I don't want to re-download the vcfs (which presumably a makefile would do). AFAIK there is no way to check using FTP whether the already-downloaded VCF files are the same (e.g. same md5sum) as the ones we have already downloaded.

Actually we could do this for the ensembl data, because ensembl allow you to get their files using rsync. So I'm coming round to the idea of having a makefile which simply `rsync`s to get the source data. But annoyingly, I think 1000genomes.ebi.ac.uk only do ftp and http (unless you know better).

**Comment by jeromekelleher** [comment]
We're probably not going to do more than 2 chromosomes for this analysis, so I don't think redownloading is a big deal. Chr20 and chr1 is probably fine.

**Comment by hyanwong** [comment]
I guess we will want to add a flag to the `convert_1kg.py` script so that we can pass a string to embed in the provenance information, then (unless there is an easy way to add it after the fact to the .samples file)?
