### ISSUE TITLE
Weight LS recombination rate by distance along the genome

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer#236]
Currently there's no concept of distance along the genome for recombination rates. We should weight the recombination rates by the distance back to the previous site (but, we need to be careful about what this means for the mutation rate).

See #235 for an example where we're not doing what we should.

**Comment by hyanwong** [comment]
Is this an easy thing to incorporate, @jeromekelleher ? It might be a nice improvement to test when E.g. Mark Ravinet is here tomorrow, messing with his sparrow data.

**Comment by jeromekelleher** [comment]
Not in that time frame, no.

**Comment by hyanwong** [comment]
OK - thought I should check. I guess we can specify it site-by-site anyway, as a workaround.

**Comment by hyanwong** [comment]
It seems like it should be easy to check whether `recombination_rate==None` and then internally set 

```
recombination_rate = np.concatenate(
    (
        [0],
        np.diff(sample_data.sites_position[:][sample_data.sites_inference])
        / sample_data.sequence_length,
    )
)
```

Which is likely to be the "standard" requirement (if people really want distance between sites not to count, they could set `recombination_map=np.full(sample_data.num_inference_sites, 1.0/sample_data.num_inference_sites))`)

We could also allow `recombination_map` to be an `msprime.RecombinationMap`, and once https://github.com/tskit-dev/msprime/issues/919 is done, convert genetic to physical distances and use the diffs that way.

However, this might be too early to start thinking about the final API, and it's unclear how we should adjust `mutation_rate` accordingly.

**Comment by jeromekelleher** [comment]
Yes, good idea. The question really is though whether we should do this automatically as part of the calculation **or** whether distance should be included as part of the recombination rate array. I'm inclined to take the latter approach as you're advocating here as it's more flexible.

**Comment by hyanwong** [comment]
You mean that we expect the user to account for distance if necessary? Note that my suggestion above also includes an addition which does parameter overloading (which you clearly don't like, see my other issue about progress monitors), but it would be sensible, I think, to be able to pass in a recombination_map which is used instead of an array of rates.

The other thing is that I think the passed-in array should be of the length of the number of sites, not the number of *inference sites*. I'm assuming that your new refactoring still ignores non-inference sites altogether, and if an array is passed in, we simply sum up all the array values from one inference site until the next (e.g. if two inference sites are separated by a single non-inference site, we take the genetic distance from the first inference site to the non-inference site and add it to the distance between the non-inference site and the second inference site, passing this sum to the  internally-used `recombination_rate` array.
