### ISSUE TITLE
Support missing data in LS copying process

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer#248]
We want to be able to support small amounts of missing data in the LS copying process. This will be indicated by a -1 in the genotype for a given sample at a give site. As implemented in https://github.com/tskit-dev/tskit/pull/489, we can update the copying process quite simply to accommodate missing data. We can then either impute (the default, I'd imagine) or preserve the missingness by snipping the edges where the haplotype for a given sample is missing.

Any thoughts @hyanwon?

Related to #169

**Comment by hyanwong** [comment]
We discussed the idea of imputing everything (easiest), then having a separate routine that masks out the missing sites by snipping out edges. This seems sensible to me. One question is whether the normal inference process has an "impute_missing" flag which runs this routine as a final step.

**Comment by hyanwong** [comment]
To do the snipping, we need access to the original SampleData file as well as the inferred TS. Given that the SampleData file is a necessary input to `match_samples`, it seems sensible to have a flag on that method that also runs the "missingness-snipping" routine as a final step.

**Comment by jeromekelleher** [comment]
We can do it inline as well during ``match_samples`` --- it's quite straightforward to do actually, so probably simplest to add it as an option ``impute_missing=True`` to ``match_samples`` I think.

**Comment by hyanwong** [comment]
A follow-up to this issue: we might like to allow missing data within an ancestor (e.g. if we are using an ancient sample as an ancestor). From [this comment](https://github.com/tskit-dev/tsinfer/blob/264861c1497ddb21f1f4d39634b8f8d265155d60/tests/test_inference.py#L993) in the test suite, it looks as if a site is all missing when reconstructing normally (i.e. without ancients), we set then site value to `0` rather than `-1`. Yet @awohns thinks that sites marked as missing in the middle of an ancestor *are* allowed, in which case I assume we should be marking these as `-1`? Can you confirm whether sites marked as `tskit.MISSING_DATA` within the middle of an otherwise intact ancestor are just skipped over (or equivalent) by the matching process,  @jeromekelleher ?

**Comment by jeromekelleher** [comment]
Missing data should be treated the same in samples and within ancestor haplotypes (ie., in the middle), so I don't see any reason this wouldn't work. I think we can close this issue all right, this functionality was implemented a while ago.

**Comment by hyanwong** [comment]
So it looks like we should make the following change in the ancestor builder, @jeromekelleher:
 
https://github.com/hyanwong/tsinfer/commit/7590f49257dd636982def9bacfd7fa72464b7ef9

Do you agree? If so I'll change the tests and also add it to the C version. This could make a difference to Wilder's HGDP-with-missing-data inferences

**Comment by jeromekelleher** [comment]
Probably - will need to look at it in more detail though.
