### ISSUE TITLE
OOM on UKBB

### ISSUE THREAD

**Issue by terhorst** [tskit-dev/tsinfer#282]
Hello! I'm getting out-of-memory errors when running `tsinfer` on UKBB data. (Specifically, on the `ms-paths` step.) I can tell from the other issues here that you have been testing on UKBB. I'm just curious if you know what is the peak memory consumption to expect? My machine has 96gb, but it seems that's not enough even for chr22. Alternatively, do you know why memory consumption shoots up for this step? Is there any way I can modify the algorithm to trade running time for memory usage? I've read the paper but don't fully understand each substep of the algorithm yet. Thanks!

Edit: I looked a bit more closely at what `ms-paths` does. It seems there is simply not enough memory to store the entire tree sequence in memory at once. Probably no solution here but to buy more RAM :)

**Comment by hyanwong** [comment]
Table 1 in the tsinfer publication lists some times & memory usage. Running on the raw UKBB data without any tweaking seemed to take 160G peak RAM. But the sparsity of SNPs in UKBB, and ascertainment bias among them, means that the generated tree sequence is really a bit rubbish, which is why we had to resort to the bespoke methods we describe in the paper (e.g. using ancestors from the thousand genomes, or pretending that some of the UKBB samples were actually ancestors). 

Also note that if you are running the development version of tsinfer, from the GitHub repo, then it could take substantially longer and use more memory, as we have been adding extra capabilities and have not fully optimised the code yet.

The treeseq-inference repo at https://github.com/mcveanlab/treeseq-inference has code for getting it all working - I'm guessing that's what you've been looking at?

**Comment by terhorst** [comment]
Thanks for the quick reply. For some reason my recollection from Table 1 was that processing chr**1** took 160gb, so I naively expected chr22 to require about 1/5th that. I am just naively running `tsinfer infer` without any other optimizations. I'll look into running the custom pipeline instead.

**Comment by hyanwong** [comment]
@terhorst I'm afraid that it was 160gb for chromosome *20*, not chromosome 1. :(

**Comment by terhorst** [comment]
@hyanwong Yeah, my mistake. Still an awesome result tho!
