### ISSUE TITLE
Rationalise SampleData model

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer#312]
There's a few places where the data model doesn't make sense, which we should fix while we're already breaking things with a major version bump.

The main thing that seems to not make much sense is how we're attaching data to ``samples``:
```
     ("samples/individual", zarr_summary(self.samples_individual)),
      ("samples/population", zarr_summary(self.samples_population)),
      ("samples/metadata", zarr_summary(self.samples_metadata)),
```

It definitely makes no sense to store population for each sample, and we're assuming that this is going to be the same for all samples in an individual in a number of places.

It's not clear to me why we'd want to store metadata on a per-sample basis, rather than on an individual. I think we probably kept this for compatibility at some point, and we should just drop it.

So, I vote we drop both ``population`` and ``metadata`` from samples, so that samples is just a way of keeping track of individuals with different ploidy that maps into the tskit data model nicely.

Any objections @hyanwong, @awohns? I think it'd be good to do this quickly after #308 drops, so that we can get these format changes out of the way before any more files are built.

**Comment by hyanwong** [comment]
> It definitely makes no sense to store population for each sample, and we're assuming that this is going to be the same for all samples in an individual in a number of places.

It's just because that's how it's done (nodes have populations, individuals don't) in tskit, for historical reasons. No need to duplicate that for sample data files, IMO.
 
> It's not clear to me why we'd want to store metadata on a per-sample basis, rather than on an individual. I think we probably kept this for compatibility at some point, and we should just drop it.

Might we not want to e.g. mark one genome as maternal and another as paternal? I can imagine other things we could associate with a sample within an individual too (e.g. what if we want metadata to percolate through to the nodes in the inferred ts). But I don't have very strong feelings about this.

> So, I vote we drop both `population` and `metadata` from samples, so that samples is just a way of keeping track of individuals with different ploidy that maps into the tskit data model nicely.

As I mentioned, it doesn't quite map onto tskit, because nodes have populations, rather than individuals having populations. But sure, go ahead.

**Comment by jeromekelleher** [comment]
Thanks - on reflection, it's not worth removing the metadata, but I've gotten rid of population in #313
